import pymongo

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["mydatabaseatividade"]
mycolPessoa = mydb["pessoa"]
mycolLivros = mydb["livros"]

listaPessoas = [
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
    {"nome": "Leonardo", "telefone": "16 91234 5678", "cidade": "Araraquara", "endereco": "Rua teste teste",
     "email": "leonardo_ignacio2010@hotmail.com", "nome_pai": "Álvaro Martins", "nome_mae": "Monica Martins"},
    {"nome": "Rubia", "telefone": "16 11111 2222", "cidade": "Curitiba", "endereco": "Rua teste 222",
     "email": "rubia@teste.com", "nome_pai": "Jose Silva", "nome_mae": "Maria Silva"},
]
listaLivros = [
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
    {"titulo": "senhor dos aneis", "descricao": "descricao teste", "anolancamento": "2019", "autor": "2222 autor",
     "editora": "bbbeditorabbb", "qtdpaginas": "548", "categoria": "aventura"},
    {"titulo": "narnia", "descricao": "DESCRICAO DESCRICAO", "anolancamento": "1998", "autor": "autor 1111",
     "editora": "aaaeditoraaaa", "qtdpaginas": "856", "categoria": "ficcao"},
]

x = mycolPessoa.insert_many(listaPessoas)
y = mycolLivros.insert_many(listaLivros)

print(x.inserted_ids)
print(y.inserted_ids)
