# Generated by Django 3.0.7 on 2020-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoComida', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('opcoes', models.CharField(max_length=50)),
                ('valorCalorico', models.DecimalField(decimal_places=4, max_digits=10)),
                ('salada', models.CharField(max_length=50)),
            ],
        ),
    ]
