# Generated by Django 3.0.7 on 2020-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='quantidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comida',
            name='valorCalorico',
            field=models.CharField(max_length=50),
        ),
    ]
